name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Project
        uses: ./actions/custom-cpp-build
        with:
          source-file: './src/asm-v3.cc'
          output-file: './src/asm-v3'
          compiler-flags: '-std=c++17 -Wall -Wextra -pedantic'   
